Game:
Position:
  Pitcher:
    x:
    y:
    z:
  Catcher:
    x:
    y:
    z:
  First:
    x:
    y:
    z:
  Second:
    x:
    y:
    z:
  Third:
    x:
    y:
    z:
  Short:
    x:
    y:
    z:
  Left:
    x:
    y:
    z:
  Center:
    x:
    y:
    z:
  Right:
    x:
    y:
    z:
  Batter:
    x:
    y:
    z:
